language: ruby

env:
  global:
    - COVERAGE=true
  matrix:
    - TEST_SUITE=unit
    - TEST_SUITE=integration

script: "bundle exec rake test:$TEST_SUITE"

rvm:
  - "1.9.3"
  - "2.1.3"
  - "ruby-head"
  - "rbx-2"
services:
  - rabbitmq
